theme: minima
title: PORTFOLIO
author: anonymous
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Frontend Engineer. Wordpress　

# social links
# twitter_username: fujisawa_sayaka # DO NOT include the @ character, or else the build will fail!
# github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
